### ISSUE TITLE
No operations allowed after connection closed in SpringBoot multiple DataSource

### ISSUE THREAD

**Issue by matrixcloud** [matrixcloud/daily-issues#5]
## My Behavior

I configured two DataSource for application, but not configured their connection pool

## Solution

add connection pool configuration to application.yml

```yml 
spring:
  profiles: docker
  cloud:
    datasource:
      url: jdbc:mysql://mysql:3306/db?useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
    consul:
      host: consul
  engine:
    datasource:
      url: jdbc:mysql://172.16.26.59:3306/ibot9?useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
```
